add html and css
artykisa/Frontend-Tasks pull request #3
Opened 2021-03-28 21:43 UTC by artykisa

2021-03-28 21:43 UTC, artykisa commented
Lab №3

2021-03-29 17:35 UTC, gmltA reviewed
What about deployment link?

2021-03-29 18:15 UTC, artykisa commented
Sorry, forgot about this. Link: https://artykisa.github.io/Frontend-Tasks/Lab3/html/track.html

2021-03-30 16:26 UTC, gmltA requested changes
Right now I can only offer you <kbd>5</kbd> after you fix all the remarks. To improve it you'll have to customise interactive elements on your website.

2021-03-30 16:26 UTC, gmltA commented on Lab3/html/addLyrics.html
> +    <br>
Use `margin` to define spacing.

2021-03-30 16:26 UTC, gmltA commented on Lab3/html/addLyrics.html
> +        </label>
Use proper layout for this, but a bunch of `br`s.

2021-03-30 16:26 UTC, gmltA commented on Lab3/html/addTrack.html
> +        </a>
Doesn't look like a link. Use another tag instead.

2021-03-30 16:26 UTC, gmltA commented on Lab3/html/editExplain.html
> +        <form class="track_text">
Why is this a `form`?

2021-03-30 20:57 UTC, artykisa commented
You can check by the same link

2021-04-05 14:18 UTC, gmltA commented on Lab3/css/addTrack.css
> +    -webkit-transform: translateY(-34px);
І адкуль

2021-04-05 14:18 UTC, gmltA commented on Lab3/css/main.css
> +    -webkit-transition: width 0.4s ease-in-out;
вы гэта

2021-04-05 14:18 UTC, gmltA commented on Lab3/css/song.css
> +    transition: all 0.3s;
скапіравалі?

Чаму ў вам ці ёсць прэфіксы, ці няма?

2021-04-05 14:21 UTC, gmltA commented
`:hover` істотна ў вас адсутнічае, а таксама стылі ў розных класах (напрыклад кнопкі) проста дубліруюцца. Гэта таксама трба было б выправіць. Пакуль што гэта <kbd>6</kbd>.

2021-04-05 15:02 UTC, artykisa commented
@gmltA Хочу уточнить могу ли я согласиться на 6 прямо сейчас или нет?

2021-04-19 19:56 UTC, gmltA approved these changes
Можаце. 6 балаў. Продана!

2021-04-19 20:18 UTC, artykisa commented
Какой лот урвал :)

2021-04-19 20:18 UTC, merged